name: gallery
description: Flutter gallery app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^5.4.2
  firebase_core: ^3.5.0
  firebase_storage: ^12.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.1.2
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0
  permission_handler: ^11.3.1
  photo_manager: ^3.3.0
  photo_manager_image_provider: ^2.1.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.12
  freezed: ^2.5.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
